version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: geth-client
    container_name: geth-bootnode
    build:
      context: .
      args:
        # - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
        - NODE_TYPE=BOOTNODE
        - SIGNER_ONE=${SIGNER_1}
        - SIGNER_TWO=${SIGNER_2}
        - SIGNER_THREE=${SIGNER_3}
    command:
    # --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodekeyhex=${NODE_KEY}
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      # --netrestrict="172.16.254.0/24"
    networks:
      - priv-eth-net

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-client
    container_name: geth-rpc-endpoint
    build:
      context: .
      args:
        - NODE_TYPE=RPCNODE
        - SIGNER_ONE=${SIGNER_1}
        - SIGNER_TWO=${SIGNER_2}
        - SIGNER_THREE=${SIGNER_3}
    depends_on:
      - geth-bootnode    
    command:
      # --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --bootnodes=${ENODE}
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      # --netrestrict="172.16.254.0/24"
    ports:
      - "8545:8545"
    networks:
      - priv-eth-net

  geth-signer-one:
    hostname: geth-signer-one
    env_file:
      - .env
    image: geth-client
    container_name: geth-signer-one
    build:
      context: .
      args:
        - NODE_TYPE=SIGNERNODE
        - SIGNER_ONE=${SIGNER_1}
        - SIGNER_TWO=${SIGNER_2}
        - SIGNER_THREE=${SIGNER_3}
    depends_on:
      - geth-bootnode
    command:
      --bootnodes=${ENODE}
      --port=30303
      --unlock=${SIGNER_1}
      --password=/tmp/${SIGNER_1}.pwd
      --mine
      --networkid=${NETWORK_ID}
      # --netrestrict="172.16.254.0/24"
    networks:
      - priv-eth-net

  geth-signer-two:
    hostname: geth-signer-two
    env_file:
      - .env
    image: geth-client
    container_name: geth-signer-two
    depends_on:
      - geth-bootnode
    command:
      --bootnodes=${ENODE}
      --port=30303
      --unlock=${SIGNER_2}
      --password=/tmp/${SIGNER_2}.pwd
      --mine
      --networkid=${NETWORK_ID}
      # --netrestrict="172.16.254.0/24"
    networks:
      - priv-eth-net

  geth-signer-three:
    hostname: geth-signer-three
    env_file:
      - .env
    image: geth-client
    container_name: geth-signer-three
    depends_on:
      - geth-bootnode
    command:
      --bootnodes=${ENODE}
      --port=30303
      --unlock=${SIGNER_3}
      --password=/tmp/${SIGNER_3}.pwd
      --mine
      --networkid=${NETWORK_ID}
      # --netrestrict="172.16.254.0/24"
    networks:
      - priv-eth-net

networks:
  priv-eth-net:
    driver: bridge
    name: priv-eth-net
    ipam:
      config:
      - subnet: 172.16.254.0/24